// import React, { useEffect, useState } from "react";
// import Loading from "./Loading";
// import { useAppContext } from "../context/AppContext";
// import toast from "react-hot-toast";

// const Community = () => {
//   const [images, setImages] = useState([]);
//   const [loading, setLoading] = useState(true);
//   const { axios } = useAppContext();

//   const fetchImages = async () => {
//     try {
//       const { data } = await axios.get("/api/user/published-images");
//       if (data.success) {
//         setImages(data.images);
//       } else {
//         toast.error(data.message);
//       }
//     } catch (error) {
//       toast.error(error.message);
//     }
//     setLoading(false);
//   };

//   useEffect(() => {
//     fetchImages();
//   }, []);

//   if (loading) return <Loading />;

//   return (
//     <div className="flex-1 p-6 md:p-10 lg:p-12 w-full mx-auto h-screen overflow-y-auto bg-slate-50/50 dark:bg-transparent scrollbar-none animate-fadeIn">
//       {/* Page Header Layout */}
//       <div className="mb-8">
//         <h2 className="text-2xl font-bold tracking-tight text-slate-800 dark:text-white">
//           Community Showcase
//         </h2>
//         <p className="text-xs text-slate-400 dark:text-slate-500 mt-1">
//           Explore outstanding artistic visuals generated by global creators
//           using QuickGPT AI.
//         </p>
//       </div>

//       {images.length > 0 ? (
//         /* Modernized Responsive Grid Column Control Center */
//         <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
//           {images.map((item, index) => (
//             <a
//               key={index}
//               href={item.imageUrl}
//               target="_blank"
//               rel="noopener noreferrer"
//               className="group relative block aspect-square rounded-2xl overflow-hidden bg-slate-100 dark:bg-white/5 border border-slate-200/60 dark:border-white/5 shadow-sm hover:shadow-xl transition-all duration-300"
//             >
//               {/* Ultra Smooth Image Scaling */}
//               <img
//                 src={item.imageUrl}
//                 alt="AI Artwork"
//                 className="w-full h-full object-cover transform group-hover:scale-[1.04] transition-transform duration-500 ease-out"
//                 loading="lazy"
//               />

//               {/* Sophisticated Premium Vignette Backdrop Layer on Hover */}
//               <div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 via-slate-950/20 to-transparent transition-opacity duration-300 flex items-end p-4">
//                 <div className="w-full transform translate-y-2 group-hover:translate-y-0 transition-transform duration-300">
//                   <span className="inline-block text-[10px] font-bold tracking-widest uppercase text-purple-400 mb-1">
//                     AI Generated
//                   </span>
//                   <p className="text-xs font-semibold text-white truncate">
//                     By {item.userName || "Anonymous"}
//                   </p>
//                 </div>
//               </div>
//             </a>
//           ))}
//         </div>
//       ) : (
//         /* Enhanced High-End Empty Layout Canvas */
//         <div className="flex flex-col items-center justify-center text-center h-[50vh] p-4 border border-dashed border-slate-200 dark:border-white/10 rounded-3xl mt-4">
//           <div className="p-4 bg-slate-100 dark:bg-white/5 rounded-full text-slate-400 dark:text-slate-500 mb-3 text-xl">
//             ✨
//           </div>
//           <h3 className="text-base font-semibold text-slate-800 dark:text-slate-200">
//             No items inside showcase yet
//           </h3>
//           <p className="text-xs text-slate-400 dark:text-slate-500 max-w-xs mt-1">
//             Be the first pioneer to generate and publish your creative prompt
//             visions directly to our open feed.
//           </p>
//         </div>
//       )}
//     </div>
//   );
// };

// export default Community;
